camunda.bpm.admin-user:
  id: admin
  password: admin

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: heyhey
    password: messiGoat
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect